spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ToyBoard2_1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true



  jpa:
    hibernate:
      ddl-auto: none # 데이터베이스 스키마 자동 업데이트
    show-sql: true # JPA SQL 로그 출력


server:
  port: 8080 # 서버 포트 설정

logging:
  level:
    org.springframework.web: DEBUG # 스프링 웹 로그 레벨 설정
